name: Run E2E tests
on: [push]
jobs:
  run-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          tools: composer:v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: node build.js
      - run: composer archive --format=zip --file=e2e
      - uses: actions/upload-artifact@v3
        with:
          name: e2e-wordpress-plugin
          path: e2e.zip
      - uses: actions/download-artifact@v3
        with:
          name: e2e-wordpress-plugin
          path: ~/download
      - run: cd ~/download && pwd && ls -R
