name: Install Easy Engine
on:
  push:
    branches:
      - smoke-testing
  pull_request:
    types: [labeled, synchronize]
jobs:
  run-e2e:
    if: contains(github.event.pull_request.labels.*.name, 'e2e-ready')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"

