name: Install Easy Engine
on:
  push:
    branches:
      - smoke-testing
  pull_request:
    types: [labeled, synchronize]
jobs:
  run-e2e:
    if: contains(github.event.pull_request.labels.*.name, format('needs{0} e2e-testing', ':')) || github.ref == 'refs/heads/smoke-testing'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: E2E tests
        run: echo "Hello"

      - name: Add "status - e2e tests passing"
        uses: actions-ecosystem/action-add-labels@v1
        if: success() && github.event_name == 'pull_request' && ! contains(github.event.pull_request.labels.*.name, format('status{0} e2e tests passing', ':'))
        with:
          labels: "status: e2e tests passing"

      - name: Remove "status - e2e tests passing" label
        uses: actions-ecosystem/action-remove-labels@v1
        if: success() && github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, format('status{0} e2e tests failing', ':'))
        with:
          labels: "status: e2e tests failing"
