name: Install Easy Engine
on:
  push:
    branches:
      - smoke-testing
  pull_request:
    types: [labeled, synchronize]
jobs:
  run-e2e:
    if: ${{ github.event.label.name == 'e2e-ready' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"

